```
Veriables -- columns
observations -- Rows
```
```
Know the data --  preprocess and organize (clean the data) -- making clustures -- analyze the data -- modells to be trained --  predictions or recommend the data
```
```
to do all these you need to know the language -- to interact with my computer to do above
```

# Header

If you want to print anything as a string you have to write it inside the cotes

In [ ]:
print ('hello world!')

hello world!


In [ ]:
print ('hello world',2+2,'this is python')

hello world 4 this is python


If you dont want to give any space between two links then use **sep** || if you want to fill something extra in between the links this will help you to add those

In [ ]:
print ('hello world',2+2,'this is python',sep='')

hello world4this is python


In [ ]:
# we can actually add the two stings togather
print ('hello'+'world')
print ('hello '+' world')#if we give space innetween the stings that will be considered
print ('hello' + 'world', sep = ' ') #sep doesnot work here
print ('hello','world', sep = ' ') #sep works only with comas

helloworld
hello  world
helloworld
hello world


In [ ]:
# we are going to know about the veriables
# veriables are something like X, y, z
ram = 12
storage =128
brand = 'apple'
price = 123
print ('the brand of the mobile phone is' + brand)
print ('the ram of the mobile phone is', ram, 'gb', sep=' ')
print ('the storage of the mobile phone is', storage, 'gb', sep=' ')
print ('the price of the mobile phone is $', price, sep='')

the brand of the mobile phone isapple
the ram of the mobile phone is 12 gb
the storage of the mobile phone is 128 gb
the price of the mobile phone is $123


In [ ]:
#we aregoing to know about bool function
# this has only true or false
is_billed = True
print (is_billed)

True


In [ ]:
# check the type of any veriables
print(type(ram))
print(type(brand))
print(type(is_billed))

<class 'int'>
<class 'str'>
<class 'bool'>


In [ ]:
type(storage)

int

In [ ]:
# what if I want to bill for 2 mobiles
bill = price + price
#or
bill = price*2
print('the total price of mobile phone is $' ,bill, sep= '')

the total price of mobile phone is $246


In [ ]:
#what if there is discount of $15 present in the total bill amount
discount = 15
after_discount = bill - discount

print(after_discount)

231


In [ ]:
#what if we want to substract
#we have the total bill amount and we need to get single phone price
Single_price = bill / 2
print (Single_price) #see here we will get 123.0 which is float

single_price1 = bill // 2
print (single_price1) #see here we will get 123 which is int

123.0
123


##Type of conversion in veriables

In [ ]:
# now we will try to convert the veriables (int, float, str) from one to another
#suppose there is a discount on the actual price of iphone of 5%
discount = price*0.05
total_price = price - discount
print('the actual price of the iphone is ' + str(total_price))
# we are converting the float to str and
# hence we could connect the two different types of veriables together with + while printing

the actual price of the iphone is 116.85


In [ ]:
#above is called as explicit conversion

print(brand + ' ' + ram + 'gb') #the ram is int and python doesnot support implicit conversion
# this will through TypeError: can only concatenate str (not "int") to str

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(brand + ' ' + str(ram) + 'gb') #explicit conversion of int to str #ram

apple 12gb


In [ ]:
a=4.5
b=int(a)
type(b)

int

In [ ]:
a="Hi"
b=int(a)
type(b) #good example of string cant be converted to int
#ValueError: invalid literal for int() with base 10: 'Hi'

ValueError: invalid literal for int() with base 10: 'Hi'

##List

In [ ]:
#Creating list
Brand_list = ['apple', 'samsung', 'oppo', 'vivo', 'sony']
price_list = [70000,40000,20000,21000,40000]
ram = [8,6,4,4,6]
Storage_list = [28,64,128,265,528]
print(Brand_list)

['apple', 'samsung', 'oppo', 'vivo', 'sony']


###Index

In [ ]:
# suppose you want to take a perticular entry from your list

print(Brand_list[2]) # see though at the 2nd position there is samsung but it gave OPPO as result
#python starts from 0 in the list

oppo


In [ ]:
print (Brand_list[2:4]) # see this is including 2 but not 4th in the list(follows exclusive method i.e. before that point will be taken)
print (price_list[1:-1]) # here one is 40000 and -1 (40000) is exclusive so 21000
print (Brand_list[-1])

['oppo', 'vivo']
[40000, 20000, 21000]
sony


##pop and Append

In [ ]:
# is you want to remove something from list then you can use it
# simple pop() will remove the last item from the list
Brand_list.pop() #removing the last item in the list i.e.sony
print (Brand_list)
Brand_list.append('Nokia') #adding last item in the list as Nokia
print (Brand_list)


['apple', 'samsung', 'oppo', 'vivo']
['apple', 'samsung', 'oppo', 'vivo', 'Nokia']


In [ ]:
#There is actually possible of change the current value of items in list with a new value
Brand_list[2] = 'MI'
print (Brand_list)

['apple', 'samsung', 'MI', 'vivo', 'sony']


##Tuple

In [ ]:
#tuple has its open and close parenthasis instead of square braquets it has the curved braquets
storage1 = (64,128,256,528)
# in tuple you can't actually change the items present in there (immutable)
storage[2]=180

# when you are selecting any list which actually you dont want to make any change there then you must create a tuple

NameError: name 'storage' is not defined

In [ ]:
X=(20,23,-50,5.6,98)
print(X[2:-1])

(-50, 5.6)


##Dictionary

In [ ]:
##dictionaries are something creating an overall table
attributes = {
    'brand' : 'apple',
    'Ram (in GB)': 4,
    'Storage (in GB)': 128,
    'price (in $)': 799
}
print (attributes)
# if you have to print any attibutes you need to specifically mention that
#there is no way of index format in dictionary

print (attributes['brand'])

{'brand': 'apple', 'Ram (in GB)': 4, 'Storage (in GB)': 128, 'price (in $)': 799}
apple


In [ ]:
products = {
    'Brand':Brand_list,
    'Ram (in GB)':ram,
    'Storage (in GB)': Storage_list,
    'price in $' : price_list
}
# see here there was already presence of Brand_list which can be used for making attributes
print(products)

{'Brand': ['apple', 'samsung', 'oppo', 'vivo', 'sony'], 'Ram (in GB)': [8, 6, 4, 4, 6], 'Storage (in GB)': [28, 64, 128, 265, 528], 'price in $': [70000, 40000, 20000, 21000, 40000]}


In [ ]:
products['Brand'][2] # to select anything from brand list

'oppo'

In [ ]:
# we can always get some keys of any perticular dictionary
keys = products.keys()
print('the key values are :\n', keys)
# here \n will help to write in new line
#to get the values in the print format for the entire dictionary
values = products.values()
print('the product values are :\n',values)



the key values are :
 dict_keys(['Brand', 'Ram (in GB)', 'Storage (in GB)', 'price in $'])
the product values are :
 dict_values([['apple', 'samsung', 'oppo', 'vivo', 'sony'], [8, 6, 4, 4, 6], [28, 64, 128, 265, 528], [70000, 40000, 20000, 21000, 40000]])


In [ ]:
dictionary2={1:"USA", 2:"India", 3:"China"}
dictionary2.pop(2)
print(dictionary2)

{1: 'USA', 3: 'China'}


##Update

In [ ]:
dictionary1={1:"USA", 2:"India", 3:"China"}
dictionary1.update({3:"Japan"})
print(dictionary1)

{1: 'USA', 2: 'India', 3: 'Japan'}


In [ ]:
products.update({'Brand'[2]:'Huwawi'})
products['Brand']

'Huwawi'

##IF statements

if (write expression):
  Body of if
else:
  Body of else

In [ ]:
price = 900
budget = int(input('please type your budget here :'))
if price <= budget:
  print('Congratulations!, you can buy an iphone')
else:
  print('Oh no!, you can not get one iphone')

please type your budget here :999
Congratulations!, you can buy an iphone


In [ ]:
storage = int(input('please type appropriate storage between 64/128/256 GB:'))
if storage == 64:
  print('the price of the phone in 600$')
elif storage == 128:
  print('the price of the phone is 750$')
elif storage == 256:
  print('the price of the phone is 900$')
else:
  print('please select appropriate storage')

please type appropriate storage between 64/128/256 GB:256
the price of the phone is 900$


In [ ]:
a = b = TRUE

if (a == b):
  print("Hello")
else:
  print("Well done")
  #Here "TRUE" is not defined so can not be compared
  #with a and b hence Python will prompt NameError: name 'TRUE' is not defined.

NameError: name 'TRUE' is not defined

In [ ]:
a = b = 'TRUE'

if (a == b):
  print("Hello")
else:
  print("Well done")

Hello


##Range

In [ ]:
range(6)

range(0, 6)

In [ ]:
list(range(6)) # it takes from 0 ends before the number you paste

[0, 1, 2, 3, 4, 5]

In [ ]:
list(range(6,14)) #starts from 6 and ends before 14

[6, 7, 8, 9, 10, 11, 12, 13]

In [ ]:
list(range(2,20,3)) # see here it starts from 2 and keeps on add 2 and provide you the number
# before 20

[2, 5, 8, 11, 14, 17]

##Itrations

In [ ]:
#itration works here from 0 to 25 how in the range of 5 how many discount can be given
price = 900
for i in range (0,30,5):
  discount = price * i/100
  Discounted_price = price - discount
  print('the discount is', i, 'the price after discount is', Discounted_price, sep=' ')


the discount is 0 the price after discount is 900.0
the discount is 5 the price after discount is 855.0
the discount is 10 the price after discount is 810.0
the discount is 15 the price after discount is 765.0
the discount is 20 the price after discount is 720.0
the discount is 25 the price after discount is 675.0


In [ ]:
## here I was trying for set an ammout of discount then give the discount price accordingly
price = 900
d=int(input('please set the discount '))
discount = price * d/100
Discounted_price = price - discount
print('the discount is', d, 'the price after discount is', Discounted_price, sep=' ')

please set the discount 2
the discount is 2 the price after discount is 882.0


In [ ]:
sum = 0
for number in range(1,5):
    sum = sum + number
print(sum)

10


##While loop

In [ ]:
# store the price (in dollars) of the mobile in variable 'Price'.
Price = 900
# set the value of i to 5
i = 5
# start the while loop
while i <= 20:
# calculate the discount amount
discount = Price * (i / 100)
# calculate the discounted price
discounted_price = Price - discount
# print the discounted price
print('The price after providing ',i, ' percent discount is $', discounted_price, sep='')
# increase the value of i by 5
i += 5
# or
# i = i + 5

In [ ]:
price = 900
i =5
while i <=20:
  discount = price * i/100
  after_discount_price= price - discount
  print('the discount is', i, 'the price after discount is', after_discount_price, sep=' ')

  i += 5

the discount is 5 the price after discount is 855.0
the discount is 10 the price after discount is 810.0
the discount is 15 the price after discount is 765.0
the discount is 20 the price after discount is 720.0


In [ ]:
i=5
while(i>0):
 i=i-1 ## started reducing from 5, 4, 3, 2, 1 before 0 stops


In [ ]:
x = [1, 2, 3, 4, 5]
while x:
  print(x.pop(0))

1
2
3
4
5


```
The length of the variable x is 5 so loop will be executed 5 times. Following will be the operation during each loop,

iteration1: x=[1, 2, 3, 4, 5] with pop(0) the element of the list with index 0 will get pop out and printed as 1
iteration1: x=[2, 3, 4, 5] with pop(0) the element of the list with index 0 will get pop out and printed as 2
iteration1: x=[3, 4, 5] with pop(0) the element of the list with index 0 will get pop out and printed as 3
iteration1: x=[4, 5] with pop(0) the element of the list with index 0 will get pop out and printed as 4
iteration1: x=[5] with pop(0) the element of the list with index 0 will get pop out and printed as 5
```

##List Comprehension

In [ ]:
price_list = [600,600,800,900,1000]
discounted_price_list=[]
for i in price_list:
  discounted_price= i - (i*5/100)
  discounted_price_list.append(discounted_price)
  print (discounted_price_list) ## see this print comes under loop

[570.0]
[570.0, 570.0]
[570.0, 570.0, 760.0]
[570.0, 570.0, 760.0, 855.0]
[570.0, 570.0, 760.0, 855.0, 950.0]


In [ ]:
price_list = [600,600,800,900,1000]
discounted_price_list=[]
for i in price_list:
  discounted_price= i - (i*5/100)
  discounted_price_list.append(discounted_price)
print (discounted_price_list) ## see this doesnot comes under loop

[570.0, 570.0, 760.0, 855.0, 950.0]


In [ ]:
price_list = [600,600,800,900,1000]
discounted_price_list=[i - (i*5/100) for i in price_list] ## we have just kept these two things together i - (i*5/100) || for i in price_list

print (discounted_price_list)

[570.0, 570.0, 760.0, 855.0, 950.0]


In [ ]:
budget = int(input('whats your budget '))

for x in discounted_price_list: ## see here how for loop came before the if
  if x <= budget:
    print ('yes')
  else:
    print ('no')

whats your budget 255
no
no
no
no
no


In [ ]:
budget = int(input('whats your budget '))
within_budget =[] ## here we are creating a list
for x in discounted_price_list: ## see here how for loop came before the if
  if x <= budget:
    within_budget.append('yes') #adding the yes if its in the budget list
  else:
    within_budget.append('no')
print (within_budget)

whats your budget 589
['yes', 'yes', 'no', 'no', 'no']


In [ ]:
##this is list comprehention method where we observerd the simplefied code
budget = int(input('whats your budget '))

within_budget = ['yes' if x <= budget else 'no' for x in discounted_price_list]
print(within_budget)

whats your budget 555
['no', 'no', 'no', 'no', 'no']


In [ ]:
week_list = [ "Week" + str(i) for i in range(5)]
print(week_list) ##here is an example where string can have loop

['Week0', 'Week1', 'Week2', 'Week3', 'Week4']


In [ ]:
repeated_list = [2] * 4
print(repeated_list)
alphabet = ['a','b','c']
for i in alphabet:
 print(i)

[2, 2, 2, 2]
a
b
c


##Functions

```
def function nane(paraneters):
   '''explain what a function does'''
  Statement(s) ##you can see the tab space which is always present after def function
```


In [ ]:
# write the function this can always be defined in the python and we can always call this funnction
def display_iphone_attributes():
  '''
  This function displays
  the stored attributes of
  the Apple iPhone
  '''
  # store the price (in dollars) of the mobile in variable 'price'
  price = 900
  # store the RAM . (in-GB) -of the mobile in variable 'ram'.
  ram = 4
  # store the internal storage (in GB) of the mobile in variable 'storage'.
  storage = 128
  # display the details
  print ('The Apple iPhone-has ', ram, 'GB RAM and ', storage, 'GB internal storage and it costs $', price, sep=' ')

In [ ]:
display_iphone_attributes() ##see we called this fuction and it poped out and I dont have to werite the codes again and again

The Apple iPhone-has  4 GB RAM and  128 GB internal storage and it costs $ 900


In [ ]:
Brand_list = ['apple', 'samsung', 'oppo', 'vivo', 'sony']
price_list = [70000,40000,20000,21000,40000]
ram = [8,6,4,4,6]
Storage_list = [28,64,128,265,528]

##you have predefined list of attibutes and now with those you want to make the definition
def display_phone_attributes(Brand_list,price_list,ram,Storage_list):
  '''
  This function displays
  the stored attributes of
  the Apple iPhone
  '''
  print (Brand_list, 'is the brand of the phone ',ram, 'GB RAM and ', Storage_list, 'GB internal storage and it costs $', price_list, sep=' ')

In [ ]:
display_phone_attributes('apple',70000,4,64) ##here we have definded the criterias and print has happend

apple is the brand of the phone  4 GB RAM and  64 GB internal storage and it costs $ 70000


In [ ]:
def func(a):
  print(a)
A = [0,1,2,3]
func(A)

[0, 1, 2, 3]


In [ ]:
def say(message, times):
    print(message*times)
say("How are you", 2)
print("How are you", 2)##see the difference

How are youHow are you
How are you 2


```
say() function takes input message and times(integer) and prints message number of times(integer) passed to it.
The message and number passed to the say() function are ''How are you" and '2' so the output is "How are youHow are you".
```

In [ ]:
# write the function
def dis_price(discount): #here we have created a definition called dis_price with one attribute which will be used in the below statements
  '''
  This function takes the discount
  percentage as input and
  returns the discounted price of Apple iPhone
  '''
  # store the price (in dollars) of the mobile in variable 'price'
  price = 900
  # calculate the price after discount
  discounted_price = price - price * (discount / 100) ##discount is used here
  # return the discounted price
  return discounted_price ## we have to return the output of discounted price

In [ ]:
dis_price(15) ##here 15 is the percent you want to discount


765.0

##Lamda function

```
instead of buch of codes in the def function
we can use lambda function to make the code short
```

In [ ]:
dis_price_lamda = lambda discount : 900 - (900 * (discount/100))
##discount act as a parameter which will always come in the parameter part and in the statement/body where you are creating the calculation

In [ ]:
dis_price_lamda(5) ## if you see the output is a flot

855.0

In [ ]:
mul = lambda a,b: return a*b
mul(5,6)

SyntaxError: invalid syntax (<ipython-input-6-b48ea2f0b14d>, line 1)

In [ ]:
(lambda x: (x+2)*5/2)(4)

15.0

In [ ]:
price_list = [70000,42000,20000,21000,45000]
for x in price_list:
  dis_price_lamda1 = lambda discount : x - (x * (discount/100))

In [ ]:
dis_price_lamda1(10)

40500.0

##Exams

In [ ]:
age = int(input('Enter your age: '))
if age < 18:
 print("Not Eligible for work")
elif age >= 18 and age <= 60:
 print("Eligible to work")
else:
 print("Too old to work as per the government rules")

Enter your age: 32
Eligible to work


In [ ]:
5 == (3+2)

True

In [ ]:
a = '5a'
int(a)

ValueError: invalid literal for int() with base 10: '5a'

In [ ]:
a = 2021
if a % 2 == 1:
 print("Number is Even")
else:
 print("Number is Odd")

Number is Even


In [ ]:
n = 8
for i in range(1, 11):
 print("{} ^ {} =".format(n, i), n**i)

8 ^ 1 = 8
8 ^ 2 = 64
8 ^ 3 = 512
8 ^ 4 = 4096
8 ^ 5 = 32768
8 ^ 6 = 262144
8 ^ 7 = 2097152
8 ^ 8 = 16777216
8 ^ 9 = 134217728
8 ^ 10 = 1073741824


In [ ]:
def mths(a, b):
 print(a + b)
 print(a - b)
 print(a * b)
 print(a // b)

mths(9, 5)

14
4
45
1


In [ ]:
def sq():
 for i in range(1, 11):
     print(i ** 2)
sq()

1
4
9
16
25
36
49
64
81
100


In [ ]:
i = '20'
if i > 20:
    print(1)
else:
    print(2)

TypeError: '>' not supported between instances of 'str' and 'int'

##args
```
It starts with the *
def function(*args/any_name)
```

If there are multiple price in a list and we need to add them we can use args

In [ ]:
def price_list(price1,price2,price3,price4):
  sum_price = price1+price2+price3+price4
  return sum_price
print ('the total of all the phone price is ', price_list(239,563,864,765))

the total of all the phone price is  2431


In [ ]:
def price_list(*prices):
  sum_price = 0 ## here the starting of sum price is zero need to be assigned
  for x in prices:
    sum_price += x ## as the number of prices keep on increasing the x will be added on and on and on

  ##return the sum Price
  return sum_price

In [ ]:
print ( 'the total of all the phone price is ',price_list(239,563,864,765))

the total of all the phone price is  2431


In [ ]:
print ( 'the total of all the phone price is ',price_list(239,563,864,765,1232,863,947,648,834))
 ##see as we increase the number of prices it will give the result after adding them

the total of all the phone price is  6955


In [ ]:
def total_anount(*prices):
  '''
  This function tokes the prices of pones ordered
  and returrs the total erder amourt.

  '''

  total = 0
  # computing the total erder amount
  for price in prices:
    total += price

  # return the total anount
  return total

In [ ]:
print ( 'the total of all the phone price is ',total_anount(239,563,864,765))

the total of all the phone price is  2431


In [ ]:
def function(var1=2, var2=4):
    var2 = 6
    var1 = 5
    print(var1, var2)

function(10, 20)

5 6


In [1]:
##suppose you want to add some more action items rather than only addition || like adding discount after the total price

def total_anount(*prices, discount = 0.0 ):
  '''here 0.0 needs to added'''
  '''
  This function tokes the prices of pones ordered
  and returrs the total erder amourt.

  '''

  total = 0
  # computing the total erder amount
  for price in prices:
    total += price

  discounted_price = total - (discount*total) ##given the condition it will automatically substract
  # return the total anount

  return discounted_price


In [2]:
print ( 'the total of all the phone price aftere discount is ',total_anount(239,563,864,765,734,764,discount=0.05)) ## see it has given the price after discount

the total of all the phone price aftere discount is  3732.55


##Kwargs
```
It starts with the two stars **
If you want to additionals actions to be performed
```
```
remember if you want to add any kwargs then you have to check it has to be in dictionary format
```

In [3]:
def total_anount(*prices, discount = 0.0, **kwargs ):
  '''here 0.0 needs to added'''
  '''
  This function tokes the prices of pones ordered
  and returrs the total erder amourt.

  '''

  total = 0
  # computing the total erder amount
  for price in prices:
    total += price

  discounted_price = total - (discount*total) ##given the condition it will automatically substract
  additional_cashback = discounted_price - kwargs['cashback']

  # return the total anount

  return additional_cashback

In [4]:
additionals = {'cashback': 5}## kwargs comes as a dictionary
print ( 'the total of all the phone price aftere discount is ',total_anount(239,563,864,765,734,764,discount=0.05, **additionals)) ## see here additionals came 2 times
## also remember before attitionals we have two stars in print aswell

the total of all the phone price aftere discount is  3727.55


In [5]:
def total_anount(*prices,**kwargs):

  '''
  This function takes the prices of phones ordered
  and any other cost additions/subtractions,
  and returns the total amount, net spend,
  and rewards points earned for the order.
  '''
  total = 0
  # computing the total order amount
  for price in prices:
    total += price

  net_spend = total - additionals['discount']*total - additionals ['cashback']

  if total >= 10000:
    reward_points = 300
  elif total >= 5000:
    reward_points = 200
  elif total >= 2000:
    reward_points = 100
  else:
    reward_points = 0

  # return the total amount
  return total, net_spend, reward_points ##here we are returning all of the different prices after discount and rewords recived

In [6]:
additionals={'discount':0.03,'cashback':5}
ta, td, tr = total_anount(239,563,864,765,734,764,**additionals) ## see here we have defined different actions in differnt key words (ta is total addition),td is discount and cashbacks, tr rewords received
print('The summery of the prices: \n', '/ntotal purchase: ', ta, 'total sepnt after all discount and cashback:',td,'total rewards recived: ', tr)

The summery of the prices: 
 /ntotal purchase:  3929 total sepnt after all discount and cashback: 3806.13 total rewards recived:  100


#Numpy and Panda

##Numpy

In [7]:
##1st tell the python to import numpy
import numpy as np

###Numpy Arrays

```
NumPy Array

. An array is a data structure that stores values of same data type.
. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to the
same data type.
. However python lists fail to deliver the performance required while computing large sets of numerical data. To address this issue we use
NumPy arrays.
. We can create NumPy arrays by converting a list to an array.
```

In [8]:
'''1st create a list '''
# defining a list of different car companies or string elements
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

# defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]

In [9]:
'''convert the list to numpy array'''

# connverting the list arr_str to a NumPy array
np_arr_str = np.array(arr_str)

# connverting the list arr_num to a NumPy array
np_arr_num = np.array(arr_num)

In [10]:
# checking the output
print ('Numpy Array (arr_str): ',np_arr_str)
print ('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num):  [5 4 6 7 3]


There is no much difference if you see between the results of normal pythonic way and numpy array

In [11]:
'''But the actual difference you will see here with data type'''

# printing the data type of lists
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num) )

# printing the data type after conversion of Lists to array
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num) )

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


```you can see here the numpy arry data type came as 'numpy.ndarray' ```

###Matrix

In [ ]:
##WE can also create matrix with numpy
'''
A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
A matrix can be created by using list of lists
'''
# Let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1], [4,5,9], [1,8, 9] ])
print(matrix)

print('Data type of matrix: ',type(matrix) )

##We see that all the NumPy objects have data type as ndarray

[[1 2 1]
 [4 5 9]
 [1 8 9]]
Data type of matrix:  <class 'numpy.ndarray'>


###Arange
```this is a numpy range you can consider```

```
There are different ways to create NumPy arrays using the functions available in NumPy library

Using np.arange() function
. The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start
is included but stop is excluded.
. It has the following paramaters:
o start : start of interval range. By default start = 0
o stop : end of interval range
o step : step size of interval. By default step size = 1
```

In [ ]:
arr2 = np.arange(start = 0, stop = 10) # 10 will be excluded from the output
print (arr2)

# or

arr2 = np.arange(0,10) ##we dont have to mention where it should start or where it should stop
print (arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
##adding steps at 2 and then print
arr3 = np.arange(start=0,stop=10,step=2)
print(arr3)

[0 2 4 6 8]


###Linspace
```Using np.linspace() function
. The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.
. It has the following parameters:
o start: start of interval range. By default start = 0
o stop: end of interval range
o num : No. of samples to generate. By default num = 50
```

NOTE: - **Linspace stops where we tell it to stop not before. And also it has default value 50 as number of equal space created between one number to another**

In [ ]:
matrix2 = np.linspace(0,5) # by default 50 evenly spaced values will be generated between 0 and 5
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
vec = np.linspace(10,20,3)
print(vec)

[10. 15. 20.]



**How are these values getting generated?**
```
The step size or the difference between each element will be decided by the following formula:
(stop- start) / (total elements - 1)
So, in this case: (5 - 0) / 49 = 0.10204082
The first value will be 0.10204082, the second valile will be 0.10204082 + 0.10204082, the third value will be 0.10204082 +0.10204082
+0.10204082, and so on.
```

In [ ]:
matrix3=np.linspace(10,20,10) ##between 10 to 20 actually 11 numbers comes
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
matrix3=np.linspace(10,20,11)
matrix3

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

**Similarly we can create matrices using the functions available in NumPy library**

**Using np.zeros()**
```
. The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy.
. It returns a matrix filled with zeros of the given shape.
. It has the following parameters:
shape : Number of rows and columns in the output matrix.
dtype: data type of the elements in the matrix, by default the value is set to float.
```

In [ ]:
matrix4= np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Using np.ones()**
```
. The np.ones() is another function for creating a matrix and performing matrix operations in NumPy.
. It returns a matrix of given shape and type, filled with ones.
. It has the following parameters:
o shape : Number of rows and columns in the output matrix.
o dtype: data type of the elements in the matrix, by default the value is set to float.
```


In [ ]:
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Using np.eye()**
```
. The np.eye() is a function for creating a matrix and performing matrix operations in NumPy.
. It returns a matrix with ones on the diagonal and zeros elsewhere.
· It has the following parameters:
o n: Number of rows and columns in the output matrix
o dtype: data type of the elements in the matrix, by default the value is set to float.
```

In [ ]:
matrix6 = np.eye(5) ##This is a identity metrix where number of rows and columns will be matching
matrix6 ##check the print properlt at diagonnaly left to right number 1 came

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

An identity matrix is a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros

In [ ]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


###Reshape

*   List item
*   List item


**We can also convert a one dimension array to a matrix. This can be done by using the np.reshape() function.**
```
· The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means
changing the shape of the given array.
. By reshaping an array we can add or remove dimensions or change number of elements in each dimension.
. In order to reshape a NumPy array, we use the reshape method with the given array.
. Syntax: array.reshape(shape)
o shape: a tuple given as input, the values in tuple will be the new shape of the array.
```

In [ ]:
arr4=np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4_reshape = arr4.reshape((2,5)) ###here we are able to reshape the upper arr4 range to a matrix format || there are total 4 paranthesis if you see
arr4_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr4 #we did not actually change the real range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4_reshape1 = arr4.reshape((2,6))
arr4_reshape1

ValueError: cannot reshape array of size 10 into shape (2,6)

this will actually throw an error as there are total 10 numbers and if it arrange 6 numbers in a single row then it actually needs 2 more numbers to fulfil the criteria of 2X6 matrix. It doesnot have so it throws an error.


**NumPy can also perform a large number of different mathematical operations and it provides different functions to do so.**
```
NumPy provides:

1. Trigonometric functions
2. Exponents and Logarithmie functions
3. Functions for arithmetic operations between arrays and matrices

Trigonometric functions
```


In [ ]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495775


In [ ]:
#This will print for all the values present in the arr4
print('Sine Function:',np.sin(arr4))
print('Cosine Function:',np.cos(arr4))
print('Tan Function',np.tan(arr4))

Sine Function: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Cosine Function: [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Tan Function [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [ ]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])



```
# This is formatted as code
```

###Exponents and Logarithms

Exponents

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
arr5 = np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

Logarithms

In [ ]:
np.log(2) ## e to the log of 2

0.6931471805599453

In [ ]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [ ]:
np.log10(2)

0.3010299956639812

###Arrythmatic

In [ ]:
l1 = [2,4,5]
l2 = [3,6,8]
print(l1+l2)
##We want 2+3,4+6,5+8
# this does not behave as you would expect!

[2, 4, 5, 3, 6, 8]


In [ ]:
# we can +-*/ arrays together

# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [ ]:
##we can do all the arrythmatic operations here
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7 ** arr8) # in python, powers are achieved using ** , NOT ^ !!! ^ does something completely different!

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


In [ ]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 =np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Power: \n', matrix7**matrix8)
print('Division: \n', matrix7/matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Power: 
 [[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


<ipython-input-23-eae5741b32bd>:5: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


**Linear algebra matrix multiplication**



In [ ]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('') ## this print will add an extra space between two prints
# taking linear algebra matrix multiplication (some may have heard this called the dot product)
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [ ]:
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
print(n1@n2)

[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]


In [ ]:
'''Transposing the metrix'''

print (matrix9)
print('')
print(np.transpose(matrix9))

# OR
print('')
print(matrix9.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print (np.max(matrix9))#maximum value

print (np.min(matrix9))#minimum value

9
1


###Random Matrix

```
np.random.rand()

np.random.randn()
```

####Rand
```
The np.random.rand returns a random NumPy array whose element(s) are drawn randomly from the uniform distribution over [0,1].
(including 0 but excluding 1)
```

In [ ]:
rand_mat1=np.random.rand(5)
print(rand_mat1) ##it gives random numbers (each time different ) which is between 0 and 1

[0.67134257 0.927698   0.52843177 0.12037161 0.89678879]


In [ ]:
rand_mat1=np.random.rand(5,5)
print(rand_mat1) ##it gives random numbers as a matrix format (each time different ) which is between 0 and 1

[[0.63112356 0.82718091 0.74636935 0.30530102 0.49088764]
 [0.04633903 0.43336778 0.7022674  0.44437629 0.2457861 ]
 [0.06449633 0.73329826 0.05136931 0.43134676 0.45855899]
 [0.44358844 0.60455175 0.03296352 0.40860401 0.49252306]
 [0.39943527 0.37235162 0.57060266 0.87684567 0.89825439]]


####randn
```
The np.random.randn returns a random NumPy array whose sample(s) are drawn randomly from the standard normal distribution
(Mean as 0 and variance as 1)
```

In [ ]:
'''randn''' ## this will distribute the number in a normalised way with mean zero and verience 1
rand_mat2=np.random.randn(5)
print(rand_mat2)

[-0.9029998   1.80571799 -0.02823402 -1.77904736 -0.91476672]


In [ ]:
rand_mat2=np.random.randn(5,5)
print(rand_mat2)

[[-0.83342785  1.26727828  0.34305536 -0.18325054 -0.40093308]
 [ 1.30196167  1.07664434  0.08796018  1.94378654  0.62390597]
 [ 0.38169241 -0.53626455  0.6828809  -1.73399786  0.22101007]
 [ 0.28650968  0.23976134  0.21237574 -1.62652606  2.02557152]
 [ 0.41658839  0.53850053  1.2391878   0.21731522 -0.25847936]]


In [ ]:
#Mean and Standerd deviation
print('Mean: ', np.mean(rand_mat2))
print('SD: ', np.std(rand_mat2))

Mean:  0.30132426539147344
SD:  0.9027473163537694


In [ ]:
import numpy as np
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
np.average(mat)

131.66666666666666

**Using np.random.randint function**
```
The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive)
range.

· Syntax - np.random.randint(low, high, size)
```
```
*   low - It represents the lowest inclusive bound of the distribution from where the sample can be drawn.
*   high - It represents the upper exclusive bound of the distribution from where the sample can be drawn.
*   size - It represents the shape of the output
```

In [ ]:
#this will draw 12 different numbers between 1 to 20
rand_mat3=np.random.randint(1,20,12)
print(rand_mat3)

[ 3  4 15 15 10 17 15 15  8  1  1  1]


In [ ]:
## we can also get the numbers as 5*5 metrix
rand_mat3=np.random.randint(1,20,[5,5])
print(rand_mat3)

[[11 10 18 15  9]
 [ 3 18  6  3  1]
 [ 7  4 16  1  4]
 [12 12 12 17  8]
 [12  2 16  3 12]]


In [ ]:
rand_arr=np.random.rand(10)
print(rand_arr)

[0.49334478 0.21905796 0.02166123 0.86648499 0.83247153 0.87025995
 0.65689305 0.15061351 0.81987915 0.7871448 ]


In [ ]:
##if you want to access the 6th index value from random entry
print(rand_arr[6])

0.6568930548488404


In [ ]:
##Get multiple entries
print(rand_arr[2:6])

[0.02166123 0.86648499 0.83247153 0.87025995]


In [ ]:
## we can also access multiple non consicutive entries using np.arrange

print('index of values to access ', np.arange(1,10,3))
print (rand_arr[np.arange(1,10,3)]) ## we used square braquets to get the index

index of values to access  [1 4 7]
[0.21905796 0.83247153 0.15061351]


Accessing arrays using logical operations

In [ ]:
##This will give all the values which are more than zero
rand_arr>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# accessing all the values of rand_arr which are greater than 0
print('Values greater than 0: ', rand_arr[rand_arr>0])

# accessing all the values of rand_arr which are less than 0
print('Values less than 0: ', rand_arr[rand_arr<0])

Values greater than 0:  [0.49334478 0.21905796 0.02166123 0.86648499 0.83247153 0.87025995
 0.65689305 0.15061351 0.81987915 0.7871448 ]
Values less than 0:  []


In [ ]:
## Assessing values from matrix
rand_matt= np.random.randn(5,5)
print(rand_matt)

[[-0.41497885 -0.5086569   0.77866563  1.37670339  1.38094393]
 [ 0.11447605 -0.15627141 -0.54621094 -0.09487496 -0.22621893]
 [ 0.42670606  0.90759953  0.58588261 -0.02141777 -0.73118152]
 [-1.25800234  0.26370557  0.92839316 -0.82871033  0.51633306]
 [ 1.51812373 -0.71078486  1.32262365  1.6164587   0.63015849]]


In [ ]:
rand_matt[2] ## this will assess the entire 2nd index row

array([ 0.42670606,  0.90759953,  0.58588261, -0.02141777, -0.73118152])

In [ ]:
print(rand_matt[2][3]) ## 2 index row and 3rd index column

#or

print(rand_matt[2,3])

-0.02141777134647654
-0.02141777134647654


In [ ]:
## we can also get range of numbers like this
''' print(rand_matt[0:2(row),1:3(column)])'''
print(rand_matt[0:2,1:3])

[[-0.5086569   0.77866563]
 [-0.15627141 -0.54621094]]


**Modify the entries in array**

In [ ]:
'''rand_matt[2(row),3(column)]'''
rand_matt[2,3]=5 #change the entry
rand_matt

array([[-0.41497885, -0.5086569 ,  0.77866563,  1.37670339,  1.38094393],
       [ 0.11447605, -0.15627141, -0.54621094, -0.09487496, -0.22621893],
       [ 0.42670606,  0.90759953,  0.58588261,  5.        , -0.73118152],
       [-1.25800234,  0.26370557,  0.92839316, -0.82871033,  0.51633306],
       [ 1.51812373, -0.71078486,  1.32262365,  1.6164587 ,  0.63015849]])

In [ ]:
rand_matt2= np.random.randn(5)
rand_matt2

array([ 0.14065708,  0.17612415, -0.63870298, -0.09035253,  0.99142414])

In [ ]:
rand_matt2[1:3]=[4,5] ## Change 2 different numbers
rand_matt2

array([ 0.14065708,  4.        ,  5.        , -0.09035253,  0.99142414])

In [ ]:
## all the matrix where more than zero changed to 56
rand_matt2[rand_matt2>0] = 56
print(rand_matt2)

[56.         56.         56.         -0.09035253 56.        ]


In [ ]:
rand_mat_1=np.random.randint(1,12,[5,5])
rand_mat_1

array([[ 8,  5, 10,  1,  1],
       [ 1,  7,  2,  7,  5],
       [ 4,  9,  8,  4, 10],
       [ 7,  6,  2,  3,  8],
       [ 5,  8,  5,  6,  5]])

In [ ]:
#you want to modify the multiple valuws in a metrixx
print('metrix before modification: \n', rand_mat_1)
rand_mat_1[1:3,2:4]=0
print('metrix after modification: \n', rand_mat_1)

metrix before modification: 
 [[ 2  3  5  7 11]
 [ 4  6  3  7  8]
 [10  8  7  6  1]
 [ 7  8  9  1  8]
 [ 8 11 11  7  6]]
metrix after modification: 
 [[ 2  3  5  7 11]
 [ 4  6  0  0  8]
 [10  8  0  0  1]
 [ 7  8  9  1  8]
 [ 8 11 11  7  6]]


In [ ]:
print(rand_mat_1) ## before creating sub matrix
print('')
## create a sub matrix from main matrix
sub_mat=rand_mat_1[1:3,2:4]
sub_mat

[[ 9  3  9  7  9]
 [ 9  3  7  4  8]
 [ 7  2  6  6  3]
 [ 9 10  4  6  4]
 [ 5  4  1  8 10]]



array([[7, 4],
       [6, 6]])

In [ ]:
## you want to modify all the values to 5 together in this sub matrix
sub_mat[:]=5


In [ ]:
print(sub_mat)
print('')
print(rand_mat_1)## we can see even if we change the submatrix the main matrix is getting impacted here

[[5 5]
 [5 5]]

[[ 9  3  9  7  9]
 [ 9  3  5  5  8]
 [ 7  2  5  5  3]
 [ 9 10  4  6  4]
 [ 5  4  1  8 10]]


```use of **copy()** can help to solve this issue```

In [ ]:
print('before creating submatrix: \n',rand_mat_1)
sub_mat=rand_mat_1[1:3,2:4].copy()
print('')
print('after creating submatrix: \n',rand_mat_1)

sub_mat[:]=3
print('')

print('after modification in sub matrix: \n', sub_mat)
print('')
print('after changing the valus in sub matrix, the parent matrix: \n', rand_mat_1)## see it did not change


before creating submatrix: 
 [[ 8  5 10  1  1]
 [ 1  7  2  7  5]
 [ 4  9  8  4 10]
 [ 7  6  2  3  8]
 [ 5  8  5  6  5]]

after creating submatrix: 
 [[ 8  5 10  1  1]
 [ 1  7  2  7  5]
 [ 4  9  8  4 10]
 [ 7  6  2  3  8]
 [ 5  8  5  6  5]]

after modification in sub matrix: 
 [[3 3]
 [3 3]]

after changing the valus in sub matrix, the parent matrix: 
 [[ 8  5 10  1  1]
 [ 1  7  2  7  5]
 [ 4  9  8  4 10]
 [ 7  6  2  3  8]
 [ 5  8  5  6  5]]


##Saving and Loading

In [ ]:
from google.colab import drive
drive.mount('/MyDrive')

Mounted at /MyDrive


In [ ]:
import numpy as np
# creating a random matrices
randint_matrix1 = np.random.randint(1,10,10). reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2 = np.random.randint(10,20,10) .reshape (2,5)
print(randint_matrix2)

[[8 9 4 9 7]
 [1 6 7 8 9]]

[[12 19 17 13 14]
 [14 18 10 11 17]]


**Using np.save() function**

**.npy** is the file name

In [ ]:
np.save('/content/drive/MyDrive/Colab_Notebook/Python_Files/saved_file_name',randint_matrix1)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab_Notebook/Python_Files/saved_file_name.npy'

**Using np.savez() function**

```
used when you want to save multiple files in a single zip file
```
**.npz** is the file name

In [ ]:
np.savez('/MyDrive/Colab_Notebook/Python_Files/multi_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)

FileNotFoundError: [Errno 2] No such file or directory: '/MyDrive/Colab_Notebook/Python_Files/multi_files.npz'

In [ ]:
#how to load files
load_file=np.load('/content/drive/MyDrive/Colab_Notebook/Python_Files/saved_file_name.npy') #here npy is the file name must be present
load_multi= np.load('/content/drive/MyDrive/Colab_Notebook/Python_Files/multi_files.npz') #here npz is the file name must be present
print(load_file)
print('')
print(load_multi)

In [ ]:
## if we want to be specific from the zip file (npz) which one shall we choose then this below
print('lst Matrix: \n', loaded_multi['randint_matrix1'])
print('2nd Matrix: \n', loaded_multi['randint_matrix2'])

new_matrix = loaded_multi['randint_matrix1']
print('New Matrix: \n',new_matrix)

In [ ]:
# here we have created the file as .txt file which can be readed by other softwares
# we can also save/load text files ... but only single variables
np.savetxt('/content/drive/MyDrive/Python Course/text_file_name.txt', randint_matrix1,delimiter=',')
rand_mat_txt = np.loadtxt('/content/drive/MyDrive/Python Course/text_file_name.txt', delimiter=',')
print(randint_matrix1)
print('')
print(rand_mat_txt)

##Pandas

*Pandas are nice way to store and manymulate data*

*Its like a spread sheet of data inside python*

**Pandas - Series and DataFrames**

Pandas Series
```
. Pandas Series is a one-dimensional labeled array/list capable of holding data of any type (integer, string, float, python objects, etc.).
· The labels are collectively called index.
. Pandas Series can be thought as a single column of an excel spreadsheet and each entry in a series corresponds to an individual row in
the spreadsheet.
```

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating a list of price of different medicines
med_price_list = [55,25,75,40,90]

# converting the med_price_list to an array
med_price_arr = np.array(med_price_list)
print(med_price_arr)
# converting the list and array into a Pandas Series object
series_list = pd.Series(med_price_list)
series_arr = pd.Series(med_price_arr)

# printing the converted series object
print(series_list)
print(series_arr)

[55 25 75 40 90]
0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64


What we have done is we have asked the panda to create a series and it has done that with an index (automatically created by python - act as an excel property).

```
We can see that the list and array have been converted to a Pandas Series object.
. We also see that the series has automatically got index labels. Let's see how these can be modified.
```

In [ ]:
# changing the index of a series
med_price_list_labeled = pd.Series(med_price_list, index = ['Omeprazole','Azithromycin', 'Metformin','Ibuprofen','Cettrizine'])
print(med_price_list_labeled)

Omeprazole      55
Azithromycin    25
Metformin       75
Ibuprofen       40
Cettrizine      90
dtype: int64


*if you see here we have named all the index as a different drug name*

In [ ]:
## if we want to add some $2.5 to wach medicine price
# adding 2.5 to existing prices
med_price_list_labeled_updated = med_price_list_labeled + 2.5
med_price_list_labeled_updated

Omeprazole      57.5
Azithromycin    27.5
Metformin       77.5
Ibuprofen       42.5
Cettrizine      92.5
dtype: float64

In [ ]:
## now we will create a new price list
new_price_list = [77, 45.5, 100, 50, 80]
new_price_list_labeled = pd.Series(new_price_list, index = ['Omeprazole','Azithromycin', 'Metformin','Ibuprofen','Cettrizine'])
print(new_price_list_labeled)

Omeprazole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cettrizine       80.0
dtype: float64


In [ ]:
##We gonna differentiate between new and old price list
print('Difference between new price and old price - ')
print(new_price_list_labeled - med_price_list_labeled_updated)

Difference between new price and old price - 
Omeprazole      19.5
Azithromycin    18.0
Metformin       22.5
Ibuprofen        7.5
Cettrizine     -12.5
dtype: float64


In [ ]:
## Dataframe -- here we can actually add the column name for students
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
df1 = pd.DataFrame(student,columns=['Student'])
df1

Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal

**Creating panda dataframe using dictionary**

In [ ]:
# defining another list
grades = ['B-', 'A+', 'A-', 'B+', 'C']
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
# creating the dataframe using a dictionary
df2 = pd.DataFrame({'Student':student, 'Grade':grades})
df2

Student Grade
0    Mary    B-
1   Peter    A+
2   Susan    A-
3    Toby    B+
4  Vishal     C

In [ ]:
## this is a panda series which is getting used as panda dataframe
year = pd.Series( [2012, 2013, 2014, 2015, 2016, 2017, 2018] )
energy_consumption = pd.Series( [2152, 2196, 2217, 2194, 2172, 2180, 2258] )

df3 = pd.DataFrame({'Year':year, 'Energy_Consumption(Mtoe) ':energy_consumption})
df3

Year  Energy_Consumption(Mtoe) 
0  2012                       2152
1  2013                       2196
2  2014                       2217
3  2015                       2194
4  2016                       2172
5  2017                       2180
6  2018                       2258

In [ ]:
# we can create a new dataframe using random values
df4 = pd.DataFrame(np.random.randn(5, 2), columns = ['Trial 1', 'Trial 2'])
df4

Trial 1   Trial 2
0 -1.026861 -2.124696
1 -1.872269  1.168142
2  0.146177  0.574135
3  0.359791  0.497586
4 -0.631570 -2.327790

In [ ]:
#giving the index with the operators as a index
operators = ['AT&T', 'Verizon', 'T-Mobile US', 'US Cellular']
revenue = [171.76, 128.29, 68.4, 4.04]

#creating a Series from lists
telecom = pd. Series(revenue, index=operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [ ]:
##accessing pandas series with index
telecom[0]

171.76

In [ ]:
telecom[:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
telecom[-2:]

T-Mobile US    68.40
US Cellular     4.04
dtype: float64

In [ ]:
##to get individual series
telecom[[2,0,3]]

T-Mobile US     68.40
AT&T           171.76
US Cellular      4.04
dtype: float64

In [ ]:
telecom['AT&T']

171.76

In [ ]:
telecom[:'T-Mobile US'] # or telecom[:2]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
# accessing multiple values
telecom[['AT&T', 'US Cellular', 'Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

**Accessing DataFrames**
```
The data of the customers visiting 24/7 Stores from different locations was collected. The data includes Customer ID, location of store, gender
of the customer, type of product purchased, quantity of products purchased, total bill amount. Let's create the dataset and see how to access
different entries of it.
```

In [ ]:
# creating the dataframe using dictionary
## panda gives all the columns to be distinct data type depending upon data
## easy to access the data
store_data = pd.DataFrame({'CustomerID': ['CustID00', 'CustID01', 'CustID02' , 'CustID03' , 'CustID04']
,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
, 'gender': ['M', 'M', 'F', 'M', 'F']
,'type': ['Electronics', 'Food&Beverages' , 'Food&Beverages', 'Medicine', 'Beauty']
,'quantity': [1,3,4, 2, 1], 'total_bill': [100, 75, 125, 50, 80] })



store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
## accessing first row
store_data[:1]

CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100

In [ ]:
#Accessing one perticular single column
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [ ]:
#accessing even alternate columns 0 2 4

print(store_data[::2]) # or

print('')
print(store_data[0:5:2])

  CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

  CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80


In [ ]:
#accessing the rows in reverse
print(store_data[::-2])

  CustomerID location gender            type  quantity  total_bill
4   CustID04   Austin      F          Beauty         1          80
2   CustID02  Seattle      F  Food&Beverages         4         125
0   CustID00  Chicago      M     Electronics         1         100


### lok and ilok

In [ ]:
store_data.loc[1]## gives the entire row

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object

In [ ]:
store_data.loc[1,'type']
## if you want a specific cell details you give 1st row index number and then 'column_name'

'Food&Beverages'

In [ ]:
store_data.iloc[2]## this also gives the entire row

CustomerID          CustID02
location             Seattle
gender                     F
type          Food&Beverages
quantity                   4
total_bill               125
Name: 2, dtype: object

In [ ]:
store_data.iloc[2,3]
## for iloc you actually need to give the index numbers for row index followed by column index

'Food&Beverages'

In [ ]:
## if you want to change one perticular cell with iloc
store_data.iloc[2,3]='Beauty'
print(store_data.iloc[2,3])

Beauty


In [ ]:
## if you want to change one perticular cell with loc
store_data.loc[2,'Beauty']='Food&Beverages'
print(store_data.loc[2,'type'])

Beauty


In [ ]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data


NameError: name 'pd' is not defined

```
Which of the following code snippet can be used to access calories burned on day2 and day3 of the dataframe calorie_data?

a) calorie_data.loc[[1,2],['calories']]

b) calorie_data.iloc[[1,2],[1]]
```
```
The calorie_data.loc[[1,2],['calories']] access the elements from row 1 and 2 corresponds to column calories.

The calorie_data.iloc[[1,2],[1]] access the elements from rows at index position 1 and 2 and also corresponds to column at index position 1.
```

In [ ]:
calorie_data.loc[[1,2],['calories']]

calories
1       300
2       345

In [ ]:
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

In [ ]:
##you can locate the data where the quantity is more than 1 but it will only give results as a true false statement
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

In [ ]:
##you can locate the data where the quantity is more than 1
store_data.loc[store_data['quantity']>1]

CustomerID       location gender            type  quantity  total_bill  \
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F          Beauty         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   

           Beauty  
1             NaN  
2  Food&Beverages  
3             NaN

In [ ]:
##adding a new column to the existing data
store_data['rating']=[2,5,3,4,4]

In [ ]:
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F          Beauty         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

           Beauty  rating  
0             NaN       2  
1             NaN       5  
2  Food&Beverages       3  
3             NaN       4  
4             NaN       4

In [ ]:
##Dropping a column from the data frame
store_data.drop(['CustomerID'],axis=1) ##here axis 1 indicates column

location gender            type  quantity  total_bill          Beauty  \
0        Chicago      M     Electronics         1         100             NaN   
1         Boston      M  Food&Beverages         3          75             NaN   
2        Seattle      F          Beauty         4         125  Food&Beverages   
3  San Francisco      M        Medicine         2          50             NaN   
4         Austin      F          Beauty         1          80             NaN   

   rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [ ]:
store_data ## see we have alrady dropped the column CustomerID but it was not dropped in true sence
## the upper command actually creates a dataframe

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F          Beauty         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

           Beauty  rating  
0             NaN       2  
1             NaN       5  
2  Food&Beverages       3  
3             NaN       4  
4             NaN       4

In [ ]:
store_data.drop(['CustomerID'],axis=1, inplace = True) ## now actually this stores the data

In [ ]:
store_data

location gender            type  quantity  total_bill          Beauty  \
0        Chicago      M     Electronics         1         100             NaN   
1         Boston      M  Food&Beverages         3          75             NaN   
2        Seattle      F          Beauty         4         125  Food&Beverages   
3  San Francisco      M        Medicine         2          50             NaN   
4         Austin      F          Beauty         1          80             NaN   

   rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [ ]:
# we can also remove multiple columns simultaneously
# it is always a good idea to store the new/updated data frames in new variables to avoid changes to the existing data frame

# creating a copy of the existing data frame
new_store_data = store_data.copy()
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [ ]:
# dropping location and rating columns simultaneously
new_store_data.drop(['location','rating'],axis=1,inplace=True)
new_store_data

CustomerID gender            type  quantity  total_bill
0   CustID00      M     Electronics         1         100
1   CustID01      M  Food&Beverages         3          75
2   CustID02      F  Food&Beverages         4         125
3   CustID03      M        Medicine         2          50
4   CustID04      F          Beauty         1          80

In [ ]:
## Dropping rows
store_data.drop(1,axis=0) ##axis 0 indicates rows
## as obvious it did not store the data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
2       3  
3       4  
4       4

In [ ]:
New_store_data= store_data.drop(1,axis=0)
## we have stored our new data in a new data frame

In [ ]:
New_store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
2       3  
3       4  
4       4

In [ ]:
## We can see in the index after 0 - 2 came
## suppose we want this to come as 0,1,2,....
New_store_data.reset_index()


index CustomerID       location gender            type  quantity  \
0      0   CustID00        Chicago      M     Electronics         1   
1      2   CustID02        Seattle      F  Food&Beverages         4   
2      3   CustID03  San Francisco      M        Medicine         2   
3      4   CustID04         Austin      F          Beauty         1   

   total_bill  rating  
0         100       2  
1         125       3  
2          50       4  
3          80       4

In [ ]:
## now we can see the new index has been created although the previous index has to be removed
New_store_data.reset_index(drop=True, inplace=True)


In [ ]:
New_store_data## see now it has followed the indexing order correcty after dropping one rows

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID02        Seattle      F  Food&Beverages         4         125   
2   CustID03  San Francisco      M        Medicine         2          50   
3   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
1       3  
2       4  
3       4

##Combining the data frames
```
There are 3 ways to do this

joins
concat
merge
```

In [ ]:
data_cust = pd.DataFrame({"customerID": ['101', '102', '103', '104'],
'category': ['Medium', 'Medium', 'High', 'Low'],
'first_visit': ['yes', 'no', 'yes', 'yes'],
'sales': [123,52,214, 663] }, index=[0, 1, 2, 3])

data_cust_new = pd.DataFrame({"customerID": ['101', '103', '104', '105'],
'distance': [12,9,44,21],
'sales': [123,214, 663, 331] }, index=[4, 5,6, 7] )

In [ ]:
pd.concat([data_cust,data_cust_new], axis=1) ## doing concat using on column

customerID category first_visit  sales customerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

In [ ]:
pd.concat([data_cust,data_cust_new], axis=0) ## doing concat using on rows

customerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [ ]:
pd.merge(data_cust,data_cust_new, on = 'customerID',how='inner') ## common fields on customerID

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [ ]:
pd.merge(data_cust,data_cust_new, on = 'customerID',how='outer') ##everything

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [ ]:
pd.merge(data_cust,data_cust_new, on = 'customerID',how='right')
## everthing in inner join and also extra present in the 2nd dataframe (105)

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [ ]:
pd.merge(data_cust,data_cust_new, on = 'customerID',how='left')
## everthing in inner join and also extra present in the 1st dataframe (102)

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123      12.0    123.0
1        102   Medium          no       52       NaN      NaN
2        103     High         yes      214       9.0    214.0
3        104      Low         yes      663      44.0    663.0

In [ ]:
data_cust.join(data_cust_new,how='right')

ValueError: columns overlap but no suffix specified: Index(['customerID', 'sales'], dtype='object')

In [ ]:
data_quarters = pd.DataFrame({'Q1': [101,102,103],
'Q2': [201,202,203]},
index=['I0', 'I1', 'I2'])

data_quarters_new = pd.DataFrame({'Q3': [301,302,303],
'Q4': [401,402,403]},
index=['I0', 'I2','I3'])

In [ ]:
data_quarters

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [ ]:
data_quarters_new

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

```
joining uses indexes (slno) of the data frame
```
```
columns must be unique
```
```
The merge() function of pandas allows us to perform standard database join
operations between dataframe or named series objects, and join() method allows
 us to join elements of a list based on their indices.
```

In [ ]:
data_quarters.join(data_quarters_new,how='right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

##Saving and loading the dataframes

In [ ]:
# Using pd. read_csv() function will work without any path if the notebook and dataset are in the folder

# data = pd. read_csv('StockData.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###Loading Data

In [ ]:
path='/content/drive/MyDrive/Colab_Notebooks/Python_Files/Stockdata.csv'
data=pd.read_csv(path)

IsADirectoryError: [Errno 21] Is a directory: '/content/drive/MyDrive/Colab_Notebooks/Python_Files'

In [ ]:
data.head()

In [ ]:
path_excel='/content/drive/MyDrive/Colab_Notebooks/Python_Files/Stockdata.xlsx'

In [ ]:
dataframe1=pd.read_excel('path_excel')

In [ ]:
dataframe1.head()

###Saving Data

In [ ]:
data.to_csv('/content/drive/MyDrive/Colab_Notebooks/Python_Files/saveData_Stockdata.csv',Index=False)

In [ ]:
data.to_excel('/content/drive/MyDrive/Colab_Notebooks/Python_Files/saveData_Stockdata.xlsx',Index=False)

###Data Information

In [ ]:
data.head()

In [ ]:
data.tail()

In [ ]:
data.shape

In [ ]:
data.info()

In [ ]:
data['price'].min()

In [ ]:
data['price'].max()

In [ ]:
data['price'].mean()

In [ ]:
data['price'].median()

In [ ]:
data['price'].mode()

In [ ]:
data['stock'].unique()

In [ ]:
data['stock'].unique()

In [ ]:
data['stock'].value_counts()

In [ ]:
data['stock'].value_counts(normalize=True)

```
A. Pandas Series.value_counts() function returns a Series containing counts of unique values.

B. On setting the normalize parameter to True, the value_counts() function returns the relative frequencies of unique values within the Series.
```

In [ ]:
data.groupby(['price'])['stock'].mean()

In [ ]:
data.groupby(['price'])['stock'].median()

```
The dataframe.groupby() function of the "Pandas" library performs one or more of the following steps:

splits the data into groups based on some criteria
applies a function to each category
combines the result based on the applied function

```

**lets suppose you want to increase the price for 10% from actual**

In [ ]:
##1st define a function
def increase(x):
  return x + x*0.1

In [ ]:
## apply will apply the increase of 10% to all the price list
data['price'].apply(increase)

```
Consider the below statements:

I. The apply() function of the "Pandas" library of Python, can be applied to both series and data frames.

II. The apply() function of the "Pandas" library of Python, returns some value after passing each row/column of a data frame with some function. The function can be both default and user-defined.
```

In [ ]:
##if you just want to save this new field in same dataframe
data['New_pice']=data['price'].apply(increase)
data.head()

In [ ]:
##Sorting the values in decending order
data.sort_values(by='New_price',ascending=False)

##converting timestamp

In [ ]:
##the american date and time has DD-MM-YYYY but we want to make this opposite order (YYYY-MM-DD) and save in the same date column
data['date']=pd.to_datetime(data['date'],dayfirst=True)

In [ ]:
data['date'].dt.strftime('%m/%d/%y')

In [ ]:
data['date'].dt.strftime('%m-%d-%y')

In [ ]:
## just pulling out the year from the date column

data['date'].dt.year

In [ ]:
data['year']=data['date'].dt.year

In [ ]:
data['date'].dt.month

In [ ]:
data['month']=data['date'].dt.month

In [ ]:
data['date'].dt.day

In [ ]:
data['day']=data['date'].dt.day

In [ ]:
## we can also check the difference between 2 different dates

data['day'][0]-data['day'][1]

In [ ]:
data['day'][0]<data['day'][1] ## gives result in true or false statement

In [ ]:
data['day'][0]>data['day'][1]